<a href="https://colab.research.google.com/github/SandeeeeeeeeepDey/data-science-11-weeks-progg/blob/main/Chapter_12_workbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensorflow like numpy?

In [ ]:
import tensorflow as tf

##Tensors and Ops

###Tensors

In [ ]:
t = tf.constant([[1.,2.,3.],[4.,5.,6.]])
t, t.shape, t.dtype

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32)>,
 TensorShape([2, 3]),
 tf.float32)

###Indexing

In [ ]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [ ]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

###Ops

In [ ]:
t+10, tf.math.add(t, 10)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[11., 12., 13.],
        [14., 15., 16.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[11., 12., 13.],
        [14., 15., 16.]], dtype=float32)>)

In [ ]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [ ]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

###Scalars

In [ ]:
tf.constant(1), tf.constant(2)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

### Keras's low-level API

In [19]:
K = tf.keras.backend
K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

In [21]:
tf.square(tf.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

### Tensors and NumPy

In [23]:
try:
    tf.constant(2.0) + tf.constant(40)
except tf.errors.InvalidArgumentError as err:
    print(err)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 


In [26]:
try:
    tf.constant(2.0) + tf.constant(40., dtype = tf.float64)
except tf.errors.InvalidArgumentError as err:
    print(err)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 


In [22]:
t2 = tf.constant(40., dtype = tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

### Variables

In [29]:
v = tf.Variable([[1.,2.,3.], [4.,5.,6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [31]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 4.,  8., 12.],
       [16., 20., 24.]], dtype=float32)>

In [32]:
v[1, 0].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 4.,  8., 12.],
       [42., 20., 24.]], dtype=float32)>

In [33]:
v[:, 2].assign([2.,3.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 4.,  8.,  2.],
       [42., 20.,  3.]], dtype=float32)>

In [34]:
v.scatter_nd_update(
    indices = [[0, 0], [1, 2]], updates = [5.,0.]
)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 5.,  8.,  2.],
       [42., 20.,  0.]], dtype=float32)>

In [36]:
sparse_delta = tf.IndexedSlices(values = [[13.,23.,3.], [43.,53.,6.]], indices = [1, 0])
v.scatter_update(sparse_delta)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[43., 53.,  6.],
       [13., 23.,  3.]], dtype=float32)>

In [37]:
try:
    v[1] = [7.,8.,9.]
except TypeError as err:
    print(err)

'ResourceVariable' object does not support item assignment


### Strings

In [39]:
tf.constant(b"hello world")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [51]:
tf.constant("caf~!@#$%^&*()_+}|{:><?}"), "cant replicate result of: ", tf.constant("café")

(<tf.Tensor: shape=(), dtype=string, numpy=b'caf~!@#$%^&*()_+}|{:><?}'>,
 'cant replicate result of: ',
 <tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>)

In [52]:
nui_code = tf.constant([ord(c) for c in "hello world"])
nui_code

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([104, 101, 108, 108, 111,  32, 119, 111, 114, 108, 100], dtype=int32)>

In [56]:
b = tf.strings.unicode_encode(nui_code, "UTF-8")
tf.strings.length(b, unit = "UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [57]:
tf.strings.unicode_decode(b, "UTF-8")

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([104, 101, 108, 108, 111,  32, 119, 111, 114, 108, 100], dtype=int32)>

## Other Data Structures