<a href="https://colab.research.google.com/github/SandeeeeeeeeepDey/data-science-11-weeks-progg/blob/main/logical_op_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# XOR using MLP in Torch

It is said that XOR operation can not be performed by single perceptrons,
**BUT**
by using Multi Layer Perceptron, it is possible.

In [1]:
import torch
from torch import nn


In [132]:
batch = { 'x1': torch.tensor([[1],[0],[1],[0]]), 'x2': torch.tensor([[1],[1],[0],[0]])}

In [22]:
class XOR(nn.Module):
  def __init__(self):
    super().__init__()
    self.weight_l0 = torch.tensor([[1,1],[1,1]])
    self.weight_l1 = torch.tensor([[-1],[1]])
    self.bias_l0 = torch.tensor([[-1.5,-0.5]])
    self.bias_l1 = torch.tensor([[-0.5]])

  def step(self,x):
    return (x >= 0).long()

  def forward(self,x):
    x1,x2 = x['x1'], x['x2']
    input_l0 = torch.cat([x1,x2], axis=1)
    output_0 = self.step(input_l0 @ self.weight_l0 + self.bias_l0)
    output_1 = self.step(output_0 @ self.weight_l1 + self.bias_l1)
    return output_1

##test

In [10]:
weight_l0 = torch.tensor([[1,1],[1,1]])
input_l0 = torch.cat([batch['x1'],batch['x2']], axis=1)
input_l0

tensor([[1, 1],
        [0, 1],
        [1, 0],
        [0, 0]])

In [14]:
bias_l0 = torch.tensor([[-1.5,-0.5]])
bias_l0

tensor([[-1.5000, -0.5000]])

In [15]:
input_l0 @ weight_l0

tensor([[2, 2],
        [1, 1],
        [1, 1],
        [0, 0]])

In [18]:
output_0 = ((input_l0 @ weight_l0 + bias_l0) >= 0).long()
output_0

tensor([[1, 1],
        [0, 1],
        [0, 1],
        [0, 0]])

In [19]:
weight_l1 = torch.tensor([[-1],[1]])
bias_l1 = torch.tensor([[-0.5]])
((output_0 @ weight_l1 + bias_l1) >= 0).long()

tensor([[0],
        [1],
        [1],
        [0]])

##Implementing

In [4]:
device = (
    'cuda'
    if torch.cuda.is_available()
    else 'cpu'
)

In [23]:
model = XOR().to(device)
batch = {k: v.to(device) for k,v in batch.items()}
model(batch)

tensor([[0],
        [1],
        [1],
        [0]])

#Idenitity Op

In [122]:
batch_i = {"a":torch.tensor([[1],[0]])}

In [125]:
class Identity(nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self,x):
    x = x['a']
    input = torch.cat([x,x], dim=1)
    operation = torch.sum(input, axis=1, keepdim = True)
    output = (operation >= 2).long()
    return output

##exp

tensor([[2, 1],
        [1, 2]])

##implement

In [131]:
identity = Identity().to(device)
identity(batch_i)

tensor([[1],
        [0]])

##AND Op

In [133]:
class AND(nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self,x):
    x1,x2 = x["x1"], x["x2"]
    #output = (x1 or x2).long() not working for some reason   #err: Boolean value of Tensor with more than one value is ambiguous
    input = torch.cat([x1,x2], axis=1)
    operation = torch.sum(input, axis=1, keepdim= True)
    output = operation >= 2
    return output.long()

##exp

In [135]:
x1,x2 = batch["x1"], batch["x2"]
#output = (x1 or x2).long() not working for some reason   #err: Boolean value of Tensor with more than one value is ambiguous
input = torch.cat([x1,x2], axis=1)
operation = torch.sum(input, axis=1, keepdim= True)
operation

tensor([[2],
        [1],
        [1],
        [0]])

##implementation

In [134]:
and_ = AND().to(device)
and_(batch)

tensor([[1],
        [0],
        [0],
        [0]])

#OR Op

In [142]:
class OR(nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self,x):
    input_1 = torch.cat([x1,x1], axis=1)
    operation_1 = torch.sum(input_1, axis=1, keepdim= True)
    input_2 = torch.cat([x2,x2], axis=1)
    operation_2 = torch.sum(input_2, axis=1, keepdim=True)

    input_final = torch.cat([input_1,input_2], dim=1)
    operation_final = torch.sum(input_final, axis=1, keepdim=True)

    output = operation_final >= 2
    return output.long()

##exp

In [141]:
x1,x2 = batch["x1"], batch["x2"]
#output = (x1 or x2).long() not working for some reason   #err: Boolean value of Tensor with more than one value is ambiguous
input_1 = torch.cat([x1,x1], axis=1)
operation_1 = torch.sum(input_1, axis=1, keepdim= True)
print(operation_1)
input_2 = torch.cat([x2,x2], axis=1)
operation_2 = torch.sum(input_2, axis=1, keepdim=True)
print(operation_2)

input_final = torch.cat([input_1,input_2], dim=1)
operation_final = torch.sum(input_final, axis=1, keepdim=True)
print(operation_final)

output = operation_final >= 2
output.long()

tensor([[2],
        [0],
        [2],
        [0]])
tensor([[2],
        [2],
        [0],
        [0]])
tensor([[4],
        [2],
        [2],
        [0]])
tensor([[ True],
        [ True],
        [ True],
        [False]])


tensor([[1],
        [1],
        [1],
        [0]])

##implementation

In [143]:
or_ = OR().to(device)
or_(batch)

tensor([[1],
        [1],
        [1],
        [0]])

#Not Op

In [ ]:
# batch_not = {'x1': torch.tensor([[1],[1],[1],[1]]), 'x2': torch.tensor([[1],[0]])}

In [150]:
class NOT(nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self,x):
    x1,x2 = x["x1"], x["x2"]
    input_1 = torch.cat([x1,x1], axis=1)
    operation_1 = torch.sum(input_1, axis=1, keepdim=True)

    operation = operation_1 + -x2
    output = operation >= 2

    return output.long()

##exp

In [149]:
x1,x2 = batch["x1"], batch["x2"]
input_1 = torch.cat([x1,x1], axis=1)
operation_1 = torch.sum(input_1, axis=1, keepdim=True)

operation = operation_1 + -x2
output = operation >= 2

output.long()

tensor([[0],
        [0],
        [1],
        [0]])

##implementation

In [151]:
not_ = NOT().to(device)
not_(batch)

tensor([[0],
        [0],
        [1],
        [0]])